[package]
name = "ui-lib"
version = "0.1.0"
authors = ["Tiffany Bennett <tiffnixen@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.20.0-alpha4"
gleam = "0.6.2"
mozangle = {version = "0.3.1", features = ["egl"]}
winapi = {version = "0.3", features = ["winerror", "d3d11", "dcomp"]}
scopeguard = "1"

[dependencies.webrender]
git = "https://github.com/servo/webrender.git"
rev = "11954418bcced3d611806541718ba951bad98765"

[dependencies.moxie]
git = "https://github.com/anp/moxie.git"
rev = "1d7b163543c6d6b6cc4696ee2dcad33a78971da9"

[dependencies.topo-macro]
git = "https://github.com/anp/moxie.git"
rev = "1d7b163543c6d6b6cc4696ee2dcad33a78971da9"

[dependencies.topo]
git = "https://github.com/anp/moxie.git"
rev = "1d7b163543c6d6b6cc4696ee2dcad33a78971da9"
