[package]
name = "moxie-native-devtools"
version = "0.1.0"
authors = ["Tiffany Bennett <tiffnixen@gmail.com>"]
edition = "2018"

[dependencies.moxie-native]
path = "../"

[dependencies.topo]
git = "https://github.com/anp/moxie.git"
rev = "1d7b163543c6d6b6cc4696ee2dcad33a78971da9"
